apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-website
  template:
    metadata:
      labels:
        app: hello-world-website
    spec:
      containers:
      - name: hello-world-website
        image: allaminapokemonbollar.azurecr.io/hello-world-website:latest
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
