apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: todo-app
 name: todo-app
spec:
 replicas: 2
 selector:
   matchLabels:
     app: todo-app
 template:
   metadata:
     labels:
       app: todo-app
   spec:
     containers:
     - image: thoba/todo-list-app
       name: todo-app
       ports:
       - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
 name: todo-app
spec:
 selector:
   app: todo-app
 ports:
 - port: 80
   targetPort: 8080
   protocol: TCP
 type: NodePort